# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Package to Private repository

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # - run: npm config rm proxy

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: http://10.10.1.210:8022/repository/pkg-group/

    - name: Publish Package to Nexus Repo
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: http://10.10.1.210:8022/repository/pkg-group/
        username: admin
        password: admin123
        # stage: Build
        # target: ./target/

    # - run: npm config set registry http://10.10.1.210:8022/repository/pkg-group/
    # - run: npm adduser --registry=http://10.10.1.210:8022/repository/pkg-release/
    # - run: npm login
    # - run: admin
    # - run: admin123

    -name: Login to repo
     uses: http://10.10.1.210:8022/repository/pkg-release/
     with:
      username: admin
      password: admin123


    -name: Publish

    # - run: npm login --registry http://10.10.1.210:8022/repository/pkg-release/
    # - run: admin
    # - run: admin123 
    - run: npm publish --registry http://10.10.1.210:8022/repository/pkg-release/ 
    



#one time step : npm config set registry http://10.10.1.210:8022/repository/pkg-group/
#one time step : npm adduser --registry=http://10.10.1.210:8022/repository/pkg-release/ 
#give username 
#password
#email
#npm login (repeated step)
