# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # registry-url: http://10.10.1.210:8022/repository/pkg-release/

    # - name: Publish Package to Nexus Repo
    #   uses: HinaMughal/test-proj@0.1.0
    #   with:
    #     serverUrl: http://10.10.1.210:8022/
    #     username: admin
    #     password: admin123
    #     format: npm
    #     repository: pkg-release
        # coordinates: directory=nexus-repo-github-action-test-rawrepodir
        # assets: filename=gh-action-test
        # filename: .//testproj

    - name: Nexus Upload
      run: curl -v -k -u username:${{secrets.NEXUS_AUTH_TOKEN}} npm publish --registry  http://10.10.1.210:8022/repository/pkg-release/


#following step of pusblish package to npm public registry by adding        


